apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: todoapp
  labels: # <-- Додаємо лейбли для ServiceMonitor
    app.kubernetes.io/name: todoapp
    app.kubernetes.io/component: web
    release: kube-prometheus-stack
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http-metrics # <---  Додаємо іменований порт